apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a47sy99fi-python 
  janus-idp.io/tekton: a47sy99fi-python
  backstage.io/kubernetes-id: a47sy99fi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a47sy99fi-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  